### ISSUE TITLE
[Suggestion] Can this plugin be applied to everything, not just PvP?

### ISSUE THREAD

**Issue by tanpro260196** [Interverse/PvPController#1]
Or is it not possible to calculate damage server-side for normal mobs?

**Comment by Interverse** [comment]
If you mean calculate custom damage coming from normal mobs, I'd look into Main.npc[] and seeing if you can modify the damage property of each mob and sending the NPC Update(23) packet to update to the client. 
If you were looking in how to apply custom damage TO npcs, I believe it is possible to calculate damage server-side by handling the NPC Strike(28) packet and/or Strike NPC with Held Item(24) packet with a plugin.

However, I don't have any plans to control server-side mob damage. This plugin filters and handles the PacketHurtV2(117) packet, so it only applies to pvp hits.
